provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  test_faas_4:
    lang: python3-http-debian
    handler: ./function
    image: localhost:5000/test_faas_4:latest
    min_replicas: 1
    build_args:
      ADDITIONAL_PACKAGE: ""
    environment:
      DIAGNOSTICS: "false"

